sonar.projectKey=ilincasoti_core
sonar.organization=ilincasoti
sonar.sources=homeassistant
sonar.exclusions=tests/**,script/**
sonar.python.version=3.11

# Pick up pytest’s XML coverage report
sonar.python.coverage.reportPaths=coverage.xml